services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER_INTEGRATION}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_INTEGRATION}
      - POSTGRES_DB=${POSTGRES_DB_INTEGRATION}
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
    container_name: ${DOCKER_CONTAINER_NAME}
volumes:
  db:
    driver: local
