services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tests
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
    container_name: bikebook-backend-integration-test-prisma
volumes:
  db:
    driver: local

